# -*- coding: utf-8 -*-
"""
TRADUZIONI DELLE SCHEDE DI FORZA (roadmap 13c, 08/10/2026).
Catalogo (it, en, es) per titoli, esercizi e prescrizioni delle 19 schede di palestra.py,
cosi' come escono da palestra.descrizione(): negli step gli apostrofi sono gia' spazi
("all altezza") e le virgolette sono gia' "secondi". Le parti tecniche (Press lap, durate,
Rest, intensity=, @80 per cento 1RM, RIR, RPE) non si toccano.
Nota: i nomi inglesi degli esercizi restano; "World s Greatest Stretch" resta com'e'.
"""
# titoli e intestazioni (con l'apostrofo: non passano da _testo)
TITOLI = [
    ("Adattamento Anatomico & Schemi Motori", "Anatomical Adaptation & Movement Patterns", "Adaptación Anatómica y Patrones Motores"),
    ("Anti-Shin Splint & IT Band", "Anti-Shin Splint & IT Band", "Anti-periostitis Tibial y Cintilla Iliotibial"),
    ("Avanzato / Massima Intensità", "Advanced / Maximum Intensity", "Avanzado / Máxima Intensidad"),
    ("Calisthenics & Viaggi", "Calisthenics & Travel", "Calistenia y Viajes"),
    ("Complementare — Cerniera d'Anca & Spinta Verticale", "Complementary — Hip Hinge & Vertical Push", "Complementaria — Bisagra de Cadera y Empuje Vertical"),
    ("Core Anti-Fatica", "Anti-Fatigue Core", "Core Antifatiga"),
    ("Corpo Libero & Eccentrico", "Bodyweight & Eccentric", "Peso Corporal y Excéntrico"),
    ("Cronometro E Salita", "Time Trial & Climbing", "Contrarreloj y Subida"),
    ("Cuffia & Mobilità Toracica", "Rotator Cuff & Thoracic Mobility", "Manguito y Movilidad Torácica"),
    ("Forza Assoluta & Reclutamento Alto", "Absolute Strength & High Recruitment", "Fuerza Absoluta y Reclutamiento Alto"),
    ("Forza Sub-Massimale", "Submaximal Strength", "Fuerza Submáxima"),
    ("Heavy Days / Periodo Fondamentale", "Heavy Days / Foundation Period", "Heavy Days / Periodo Fundamental"),
    ("Ottimizzata — Forza Massimale & Spinta", "Optimized — Maximal Strength & Push", "Optimizada — Fuerza Máxima y Empuje"),
    ("Postura Crono/Aero & Catena Posteriore", "TT/Aero Posture & Posterior Chain", "Postura Crono/Aero y Cadena Posterior"),
    ("Potenza & Reattività Neuromuscolare", "Power & Neuromuscular Reactivity", "Potencia y Reactividad Neuromuscular"),
    ("Potenza Nuoto", "Swim Power", "Potencia de Natación"),
    ("Potenza Rotazionale", "Rotational Power", "Potencia Rotacional"),
    ("Potenza Specifica Ciclismo", "Cycling-Specific Power", "Potencia Específica de Ciclismo"),
    ("Prehab, Arco Plantare, Bacino e Cuffia", "Prehab, Foot Arch, Pelvis & Cuff", "Prehab, Arco Plantar, Pelvis y Manguito"),
    ("Prevenzione Infortuni Runner", "Runner Injury Prevention", "Prevención de Lesiones del Corredor"),
    ("Prevenzione Spalla Swimmer", "Swimmer Shoulder Prevention", "Prevención del Hombro del Nadador"),
    ("Principiante / Onboarding", "Beginner / Onboarding", "Principiante / Inicio"),
    ("Resilienza Corsa", "Running Resilience", "Resiliencia en Carrera"),
    ("Rigenerazione & Mobilità Attiva", "Regeneration & Active Mobility", "Regeneración y Movilidad Activa"),
    ("Scarico Neurale e Prontezza Gara", "Neural Unloading & Race Readiness", "Descarga Neural y Preparación para Carrera"),
    ("Solidità nelle Fasi Finali di Corsa", "Solidity in the Final Stages of the Run", "Solidez en las Fases Finales de Carrera"),
    ("Stabilità Bici", "Bike Stability", "Estabilidad en Bicicleta"),
    ("Stiffness, Tendine d'Achille & Bacino", "Stiffness, Achilles Tendon & Pelvis", "Rigidez, Tendón de Aquiles y Pelvis"),
    ("Trasferimento di Potenza Multi-planare", "Multi-planar Power Transfer", "Transferencia de Potencia Multiplanar"),
    ("Trasferta In Hotel", "Hotel Trip", "En el Hotel"),
    ("Trazione, Rotazione & Assetto", "Pull, Rotation & Alignment", "Tracción, Rotación y Alineación"),
    ("Zero Attrezzatura / High Volume Resilienza", "Zero Equipment / High Volume Resilience", "Sin Material / Resiliencia de Alto Volumen"),
    ("Schema palestra", "Gym plan", "Plan de gimnasio"),
    ("Forza", "Strength", "Fuerza"),
]

# esercizi (gli apostrofi negli step sono gia' spazi)
ESERCIZI = [
    ("(o Plank con mani su fitball e cerchi dinamici)", "(or Plank with hands on a fitball and dynamic circles)", "(o Plancha con manos en fitball y círculos dinámicos)"),
    ("Affondi laterali con kettlebell", "Lateral lunges with kettlebell", "Zancadas laterales con kettlebell"),
    ("Affondi posteriori dinamici", "Dynamic reverse lunges", "Zancadas hacia atrás dinámicas"),
    ("Affondi sul posto con torsione del tronco", "Lunges in place with trunk twist", "Zancadas en el sitio con torsión del tronco"),
    ("Affondo basso con estensione toracica", "Low lunge with thoracic extension", "Zancada baja con extensión torácica"),
    ("Affondo bulgaro (piede posteriore sul letto o sedia)", "Bulgarian lunge (rear foot on the bed or a chair)", "Zancada búlgara (pie trasero sobre la cama o una silla)"),
    ("Affondo posteriore con rotazione del busto con palla medica", "Reverse lunge with torso rotation and medicine ball", "Zancada atrás con rotación del torso y balón medicinal"),
    ("con braccia tese avanti", "with arms straight forward", "con brazos extendidos al frente"),
    ("a muro per dorsiflessione caviglia", "at the wall for ankle dorsiflexion", "en la pared para dorsiflexión del tobillo"),
    ("(Superman isometrico a gambe e braccia tese)", "(isometric Superman with straight legs and arms)", "(Superman isométrico con piernas y brazos extendidos)"),
    ("ampi controllati", "wide and controlled", "amplios y controlados"),
    ("e rotazioni toraciche", "and thoracic rotations", "y rotaciones torácicas"),
    ("su panca romana", "on the Roman chair", "en banco romano"),
    ("per spalle", "for shoulders", "para hombros"),
    ("all altezza del petto", "at chest height", "a la altura del pecho"),
    ("isometrico (ginocchia a 2 cm da terra)", "isometric (knees 2 cm off the floor)", "isométrico (rodillas a 2 cm del suelo)"),
    ("con estensione diagonale e fermo", "with diagonal extension and hold", "con extensión diagonal y pausa"),
    ("con ginocchia staccate da terra", "with knees off the floor", "con rodillas despegadas del suelo"),
    ("lento con pausa", "slow with a pause of", "lento, pausa de"),   # es: non ripetere la frase italiana
    ("in massima estensione", "at full extension", "en máxima extensión"),
    ("(o Step-Up su box)", "(or Step-Up on a box)", "(o Step-Up en cajón)"),
    ("(dall alto verso il basso)", "(high to low)", "(de arriba abajo)"),
    ("bipodalico a terra con salita rapida", "double-leg on the floor with fast rise", "bipodal en el suelo con subida rápida"),
    ("isometrico a metà altezza (ginocchio dritto o piegato)", "isometric at half height (knee straight or bent)", "isométrico a media altura (rodilla recta o flexionada)"),
    ("Camminata del cameriere (Waiter s Walk, un braccio alto e uno basso)", "Waiter walk (one arm high, one low)", "Paseo del camarero (Waiter walk, un brazo arriba y otro abajo)"),
    ("Camminata su talloni a punte sollevate", "Heel walk with toes raised", "Caminar sobre talones con puntas elevadas"),
    ("Camminata sulle punte dei piedi a ginocchia dritte", "Toe walk with straight knees", "Caminar de puntillas con rodillas rectas"),
    ("con respirazione diaframmatica", "with diaphragmatic breathing", "con respiración diafragmática"),
    ("con respirazione profonda", "with deep breathing", "con respiración profunda"),
    ("con respirazione", "with breathing", "con respiración"),
    ("su gomiti", "on elbows", "sobre codos"),
    ("Child s Pose con focus su espansione dorsale", "Child Pose focusing on back expansion", "Child Pose con foco en la expansión dorsal"),
    ("Circonduzioni spalle con elastico", "Shoulder circles with band", "Circunducciones de hombros con banda"),
    ("con mini-band attorno alle ginocchia", "with mini-band around the knees", "con minibanda alrededor de las rodillas"),
    ("a leva corta (ginocchio in appoggio)", "short lever (knee supported)", "de palanca corta (rodilla apoyada)"),
    ("su panca (adduzione anca)", "on a bench (hip adduction)", "en banco (aducción de cadera)"),
    ("con elastico teso tra mani e ginocchia", "with band stretched between hands and knees", "con banda tensa entre manos y rodillas"),
    ("con mini-band sui piedi", "with mini-band on the feet", "con minibanda en los pies"),
    ("Dips per tricipiti su sedia solida", "Triceps dips on a sturdy chair", "Fondos de tríceps en una silla firme"),
    ("(Cane a testa in giù alternato a cobra)", "(downward dog alternating with cobra)", "(perro boca abajo alternado con cobra)"),
    ("facilitato (o Leg Raise su panca inclinata)", "assisted (or Leg Raise on an incline bench)", "asistido (o Leg Raise en banco inclinado)"),
    ("da gradino basso (15-20 cm)", "from a low step (15-20 cm)", "desde un escalón bajo (15-20 cm)"),
    ("Estensioni d anca al cavo o con mini-band", "Hip extensions on the cable or with mini-band", "Extensiones de cadera en polea o con minibanda"),
    ("Extra-rotatori con banda elastica", "External rotators with elastic band", "Rotadores externos con banda elástica"),
    ("Extra-rotazione con elastico (gomito aderente al fianco o a 90°)", "External rotation with band (elbow at the side or at 90°)", "Rotación externa con banda (codo pegado al costado o a 90°)"),
    ("Extrarotazione a 90° al cavo basso o con elastico", "External rotation at 90° on the low cable or with band", "Rotación externa a 90° en polea baja o con banda"),
    ("al cavo o con elastico", "on the cable or with band", "en polea o con banda"),
    ("con fune mirato a livello della fronte", "with rope aimed at forehead level", "con cuerda a la altura de la frente"),
    ("con due manubri moderati", "with two moderate dumbbells", "con dos mancuernas moderadas"),
    ("con due manubri pesanti", "with two heavy dumbbells", "con dos mancuernas pesadas"),
    ("banda ileotibiale e piriforme", "IT band and piriformis", "cintilla iliotibial y piriforme"),
    ("quadricipiti e glutei", "quads and glutes", "cuádriceps y glúteos"),
    ("tratto toracico (estensioni)", "thoracic spine (extensions)", "zona torácica (extensiones)"),
    ("bipodalico isometrico con cuscino stretto tra le ginocchia", "double-leg isometric squeezing a cushion between the knees", "bipodal isométrico apretando un cojín entre las rodillas"),
    ("bipodalico con elastico alle ginocchia", "double-leg with band at the knees", "bipodal con banda en las rodillas"),
    ("bipodalico a terra", "double-leg on the floor", "bipodal en el suelo"),
    ("su una gamba", "on one leg", "a una pierna"),
    ("su box (seduta e risalita controllata)", "to a box (controlled sit and rise)", "a cajón (sentada y subida controlada)"),
    ("con bilanciere o manubrio", "with barbell or dumbbell", "con barra o mancuerna"),
    ("(stacco unilaterale da terra)", "(single-side deadlift from the floor)", "(peso muerto unilateral desde el suelo)"),
    ("con transizione dinamica da seduti", "with dynamic transition while seated", "con transición dinámica sentado"),
    ("senza supporto", "unsupported", "sin apoyo"),
    ("in quadrupedia", "on all fours", "en cuadrupedia"),
    ("(focus spinta dai talloni)", "(focus on pushing through the heels)", "(foco en empujar con los talones)"),
    ("(dondolio mantenendo la posizione a banana)", "(rocking while holding the banana position)", "(balanceo manteniendo la posición de banana)"),
    ("con braccia lungo i fianchi", "with arms along the sides", "con brazos a lo largo del cuerpo"),
    ("senza piegamento", "without push-up", "sin flexión"),
    ("a una mano", "one-handed", "a una mano"),
    ("presa neutra", "neutral grip", "agarre neutro"),
    ("su panca con schiena piatta a terra", "on a bench with the back flat", "en banco con la espalda plana"),
    ("frontali e laterali", "front and lateral", "frontales y laterales"),
    ("simulato", "simulated", "simulado"),
    ("con manubri o bilanciere in piedi", "with dumbbells or barbell, standing", "con mancuernas o barra, de pie"),
    ("con bilanciere in piedi", "with barbell, standing", "con barra, de pie"),
    ("Mobilità caviglie con banda elastica", "Ankle mobility with elastic band", "Movilidad de tobillos con banda elástica"),
    ("Mobilità caviglie con elastico a muro", "Ankle mobility with band at the wall", "Movilidad de tobillos con banda en la pared"),
    ("Mobilità toracica in quadrupedia", "Thoracic mobility on all fours", "Movilidad torácica en cuadrupedia"),
    ("con elastico sulle caviglie", "with band at the ankles", "con banda en los tobillos"),
    ("assistito con elastico o mani", "assisted with band or hands", "asistido con banda o manos"),
    ("ai cavi o elastico", "on cables or band", "en poleas o banda"),
    ("isometrico con elastico", "isometric with band", "isométrico con banda"),
    ("orizzontale con isometria", "horizontal with isometric hold of", "horizontal con isometría de"),
    ("a braccia tese", "with straight arms", "con brazos extendidos"),
    ("Panca inclinata con manubri", "Incline dumbbell press", "Press inclinado con mancuernas"),
    ("Piegamenti classici (piedi rialzati se facili)", "Classic push-ups (feet raised if easy)", "Flexiones clásicas (pies elevados si son fáciles)"),
    ("Piegamenti classici con mani su rialzo se stanchi", "Classic push-ups with hands raised if tired", "Flexiones clásicas con manos elevadas si estás cansado"),
    ("(spinta verticale)", "(vertical push)", "(empuje vertical)"),
    ("a terra sui gomiti", "on the floor on elbows", "en el suelo sobre los codos"),
    ("classico sui gomiti con avanzamento su punte", "classic on elbows with toe walk-forward", "clásica sobre codos con avance de puntillas"),
    ("con estensione alternata di un braccio in linea retta", "with alternating straight-arm reach", "con extensión alterna de un brazo en línea recta"),
    ("a caviglie rigide", "with stiff ankles", "con tobillos rígidos"),
    ("Polpacci al muro in allungamento dinamico", "Calves at the wall in dynamic stretch", "Gemelos en la pared con estiramiento dinámico"),
    ("Ponte glutei monopodalico con piede su rialzo", "Single-leg glute bridge with foot raised", "Puente de glúteos a una pierna con pie elevado"),
    ("a terra con pollici verso l alto", "on the floor with thumbs up", "en el suelo con pulgares hacia arriba"),
    ("Pullover con manubrio su panca piana", "Dumbbell pullover on a flat bench", "Pullover con mancuerna en banco plano"),
    ("(impulso gambe)", "(leg drive)", "(impulso de piernas)"),
    ("con mani su manubri (presa a martello)", "with hands on dumbbells (hammer grip)", "con manos en mancuernas (agarre martillo)"),
    ("facilitati con mani su panca", "assisted with hands on a bench", "asistidas con manos en banco"),
    ("Rematore a petto in appoggio su panca 30°", "Chest-supported row on a 30° bench", "Remo con pecho apoyado en banco a 30°"),
    ("Rematore ai cavi presa larga con gomiti aperti", "Wide-grip cable row with elbows out", "Remo en polea con agarre ancho y codos abiertos"),
    ("Rematore al petto con due manubri su panca inclinata", "Two-dumbbell chest-supported row on an incline bench", "Remo con dos mancuernas en banco inclinado"),
    ("Rematore al petto con manubri su panca a 45°", "Chest-supported dumbbell row on a 45° bench", "Remo con mancuernas en banco a 45°"),
    ("Rematore con bilanciere o manubrio", "Barbell or dumbbell row", "Remo con barra o mancuerna"),
    ("Rematore inverso (sotto tavolo robusto o sbarra bassa)", "Inverted row (under a sturdy table or low bar)", "Remo invertido (bajo una mesa firme o barra baja)"),
    ("Rematore unilaterale su panca con partenza da fermo (dead-stop)", "Single-arm bench row from a dead stop (dead-stop)", "Remo unilateral en banco desde parado (dead-stop)"),
    ("Respirazione diaframmatica a pancia in giù (Crocodile Breathing)", "Prone diaphragmatic breathing (Crocodile Breathing)", "Respiración diafragmática boca abajo (Crocodile Breathing)"),
    ("Reverse Hyper o Estensioni alla panca romana", "Reverse Hyper or Roman chair extensions", "Reverse Hyper o extensiones en banco romano"),
    ("sul bordo del letto", "on the edge of the bed", "en el borde de la cama"),
    ("Rotazioni lente della testa e del collo", "Slow head and neck rotations", "Rotaciones lentas de cabeza y cuello"),
    ("Rotolamento pianta del piede con pallina da lacrosse", "Foot sole rolling with a lacrosse ball", "Rodar la planta del pie con pelota de lacrosse"),
    ("Rotolamento pianta del piede su pallina dura", "Foot sole rolling on a hard ball", "Rodar la planta del pie sobre una pelota dura"),
    ("con disco/manubrio leggero", "with light plate or dumbbell", "con disco o mancuerna ligera"),
    ("Salto laterale da fermo (Heiden jump) con atterraggio stabilizzato", "Standing lateral jump (Heiden jump) with stabilized landing", "Salto lateral desde parado (Heiden jump) con aterrizaje estabilizado"),
    ("(trazioni solo di scapola, braccia tese)", "(scapular-only pull-ups, straight arms)", "(dominadas solo de escápula, brazos extendidos)"),
    ("(o in piedi con ginocchio piegato a 45°)", "(or standing with knee bent at 45°)", "(o de pie con rodilla flexionada a 45°)"),
    ("(piegamenti solo scapolari)", "(scapular-only push-ups)", "(flexiones solo escapulares)"),
    ("monopodalico a piedi nudi", "single-leg barefoot", "a una pierna descalzo"),
    ("con abduzione gamba libera", "with free-leg abduction", "con abducción de la pierna libre"),
    ("con abduzione gamba tesa", "with straight-leg abduction", "con abducción de la pierna extendida"),
    ("con bacino alto", "with hips high", "con cadera alta"),
    ("con clamshell simultaneo", "with simultaneous clamshell", "con clamshell simultáneo"),
    ("con spinta del ginocchio superiore al petto", "driving the top knee to the chest", "llevando la rodilla superior al pecho"),
    ("(tallone ruotato in alto e indietro)", "(heel turned up and back)", "(talón girado hacia arriba y atrás)"),
    ("con atterraggio stabilizzato", "with stabilized landing", "con aterrizaje estabilizado"),
    ("leggero a terra", "light, on the floor", "ligero en el suelo"),
    ("a due gambe (o fitball leg curl)", "two legs (or fitball leg curl)", "a dos piernas (o fitball leg curl)"),
    ("Sollevamento ginocchio al petto al cavo o con mini-band", "Knee drive to chest on the cable or with mini-band", "Elevación de rodilla al pecho en polea o con minibanda"),
    ("con reach", "with reach", "con alcance"),
    ("con apertura toracica", "with thoracic opening", "con apertura torácica"),
    ("con rotazione toracica", "with thoracic rotation", "con rotación torácica"),
    ("con distensione ginocchio posteriore", "with rear knee extension", "con extensión de la rodilla trasera"),
    ("Stacco Rumeno", "Romanian Deadlift", "Peso muerto rumano"),
    ("Step-Down laterale da gradino basso (focus ginocchio in asse)", "Lateral step-down from a low step (focus on knee alignment)", "Step-down lateral desde escalón bajo (foco en la rodilla alineada)"),
    ("esplosivo su box con manubri", "explosive onto a box with dumbbells", "explosivo en cajón con mancuernas"),
    ("su box (altezza ginocchio)", "onto a box (knee height)", "en cajón (altura de rodilla)"),
    ("ai cavi (braccia tese)", "on cables (straight arms)", "en poleas (brazos extendidos)"),
    ("(mani sovrapposte a terra, braccia distese avanti)", "(hands stacked on the floor, arms extended forward)", "(manos superpuestas en el suelo, brazos extendidos al frente)"),
    ("con manubrio molto pesante", "with a very heavy dumbbell", "con mancuerna muy pesada"),
    ("Superman alternato a croce", "Alternating cross Superman", "Superman alterno cruzado"),
    ("in buca", "in the hole", "abajo"),
    ("su talloni contro parete", "on heels against the wall", "sobre talones contra la pared"),
    ("contro parete", "against the wall", "contra la pared"),
    ("Toe Yoga (sollevamento alluce alternato alle 4 dita)", "Toe Yoga (big toe raise alternating with the other 4 toes)", "Toe Yoga (elevación del dedo gordo alternada con los otros 4 dedos)"),
    ("(o Stacco da terra convenzionale)", "(or conventional deadlift)", "(o peso muerto convencional)"),
    ("presa alta", "high grip", "agarre alto"),
    ("Trazioni alla sbarra", "Pull-ups on the bar", "Dominadas en barra"),
    ("Trazioni con sovraccarico alla cintura", "Belt-weighted pull-ups", "Dominadas con lastre en el cinturón"),
    ("Trazioni zavorrate (o Lat Machine pesante)", "Weighted pull-ups (or heavy lat pulldown)", "Dominadas lastradas (o jalón pesado)"),
    ("Trazioni zavorrate presa prona (o Lat Machine)", "Weighted pronated pull-ups (or lat pulldown)", "Dominadas lastradas en pronación (o jalón)"),
    ("Y-T-W con manubri leggeri a pancia in giù", "Prone Y-T-W with light dumbbells", "Y-T-W boca abajo con mancuernas ligeras"),
    ("Lat Machine", "Lat pulldown", "Jalón al pecho"),
    ("su panca", "on a bench", "en banco"),
    ("su gradino", "on a step", "en escalón"),
    ("sul posto", "in place", "en el sitio"),
    ("a corpo libero", "bodyweight", "con peso corporal"),
    ("con discesa in", "with lowering in", "con bajada en"),
    ("con manubri", "with dumbbells", "con mancuernas"),
    ("con manubrio", "with dumbbell", "con mancuerna"),
    ("con bilanciere", "with barbell", "con barra"),
    ("su ginocchia", "on knees", "de rodillas"),
    ("a terra", "on the floor", "en el suelo"),
    ("assistito", "assisted", "asistido"),
    ("compatto", "compact", "compacto"),
    ("controllati", "controlled", "controlados"),
    ("pesante", "heavy", "pesado"),
    ("isometrico", "isometric", "isométrico"),
    ("(o", "(or", "(o"),
]

# prescrizioni (dopo "— ") e parole comuni negli step
PRESCRIZIONI = [
    ("lato destro", "right side", "lado derecho"),
    ("lato sinistro", "left side", "lado izquierdo"),
    ("con disco al petto", "with plate on the chest", "con disco al pecho"),
    ("con enfasi sull allungamento", "emphasizing the stretch", "con énfasis en el estiramiento"),
    ("sotto il parallelo", "below parallel", "por debajo del paralelo"),
    ("al parallelo", "at parallel", "en paralelo"),
    ("profondità parallelo", "depth to parallel", "profundidad paralela"),
    ("risalita esplosiva", "explosive drive up", "subida explosiva"),
    ("passi avanti", "steps forward", "pasos adelante"),
    ("passi indietro", "steps back", "pasos atrás"),
    ("con contrazione", "with squeeze", "con contracción"),
    ("rimbalzi veloci, ginocchia tese", "quick bounces, straight knees", "rebotes rápidos, rodillas extendidas"),
    ("a salire", "going up", "al subir"),
    ("a scendere", "going down", "al bajar"),
    ("avanti/indietro", "forward/back", "adelante/atrás"),
    ("con rimbalzo reattivo", "with reactive rebound", "con rebote reactivo"),
    ("con massima elevazione e atterraggio morbido", "with maximum height and soft landing", "con máxima elevación y aterrizaje suave"),
    ("caduta controllata", "controlled drop", "caída controlada"),
    ("al picco", "at the peak", "en el pico"),
    ("massima apertura dorsale", "full back opening", "máxima apertura dorsal"),
    ("al petto", "at the chest", "en el pecho"),
    ("focus bacino indietro", "focus hips back", "foco en la cadera atrás"),
    ("in basso", "at the bottom", "abajo"),
    ("in alto", "at the top", "arriba"),
    ("senza spinta del piede a terra", "without pushing off the foot", "sin empujar con el pie en el suelo"),
    ("con snap d anca violento e massima accelerazione", "with a violent hip snap and maximum acceleration", "con golpe de cadera violento y máxima aceleración"),
    ("in massimo allungamento", "at maximum stretch", "en máximo estiramiento"),
    ("per diagonale", "per diagonal", "por diagonal"),
    ("per posizione", "per position", "por posición"),
    ("x gamba", "per leg", "por pierna"),
    ("x lato", "per side", "por lado"),
    ("x braccio", "per arm", "por brazo"),
    ("x piede", "per foot", "por pie"),
    ("per gamba", "per leg", "por pierna"),
    ("per lato", "per side", "por lado"),
    ("per piede", "per foot", "por pie"),
    ("per cento", "percent", "por ciento"),
    ("con fermo", "with hold", "con pausa"),
    ("fermo", "hold", "pausa"),
    ("discesa", "lowering", "bajada"),
    ("distensione", "extension", "extensión"),
    ("allungamento", "stretch", "estiramiento"),
    ("pausa", "pause", "pausa"),
    ("secondi", "seconds", "segundos"),
    ("secondo", "second", "segundo"),
    ("lente", "slow", "lentas"),
    ("lenti", "slow", "lentas"),
    ("veloci", "fast", "rápidas"),
    ("pesanti", "heavy", "pesadas"),
    ("esplosive", "explosive", "explosivas"),
    ("alternate", "alternating", "alternas"),
    ("controllate", "controlled", "controladas"),
    ("totali", "total", "totales"),
    ("metri", "meters", "metros"),
    ("molleggi", "bounces", "rebotes"),
    ("transizioni", "transitions", "transiciones"),
    ("cambi", "switches", "cambios"),
    ("salti", "jumps", "saltos"),
    ("rip", "reps", "rep"),
    ("con", "with", "con"),
    ("e", "and", "y"),
]
